include:
  - project: 'to-be-continuous/node'
    ref: '3.5.3'
    file: '/templates/gitlab-ci-node.yml'

variables:
  NODE_IMAGE: dockerproxy.repos.tech.orange/node:lts-alpine
  NODE_CONFIG_REGISTRY: https://repos.tech.orange/artifactory/api/npm/npmproxy/
  NODE_MANAGER: yarn
  NODE_TEST_ARGS: test

node-build:
  script:
    # FIXME: try headless launch unit test and code coverage
    #- $NODE_MANAGER $NODE_TEST_ARGS
    - if [[ "$NODE_BUILD_DISABLED" != "true" ]]; then $NODE_MANAGER $NODE_BUILD_ARGS; fi

