include:
  - project: 'to-be-continuous/node'
    ref: '3.5.3'
    file: '/templates/gitlab-ci-node.yml'

variables:
  NODE_IMAGE: dockerproxy.repos.tech.orange/node:lts-alpine
  NODE_CONFIG_REGISTRY: https://repos.tech.orange/artifactory/api/npm/npmproxy/
  NODE_MANAGER: yarn
  NODE_TEST_ARGS: test

