/*
 * Copyright (c) 2023-2025 Orange. All rights reserved.
 * This software is distributed under the BSD 3-Clause-clear License, the text of which is available
 * at https://spdx.org/licenses/BSD-3-Clause-Clear.html or see the "LICENSE" file for more details.
 */

/**
 * Enumeration for information data types used in information blocks
 */
export enum INFO_DATA_TYPES {
  SAMPLE_PERCENTAGE = 'GLOBAL.SAMPLE_PERCENTAGE',
  INSTANCES = 'GLOBAL.INSTANCES',
  EVALUATED_VARIABLES = 'GLOBAL.EVALUATED_VARIABLES',
  LEARNING_TASK = 'GLOBAL.LEARNING_TASK',
  DICTIONARY = 'GLOBAL.DICTIONARY',
  DATABASE = 'GLOBAL.DATABASE',
  VARIABLES = 'GLOBAL.VARIABLES',
  TARGET_VARIABLE = 'GLOBAL.TARGET_VARIABLE',
  SAMPLING_MODE = 'GLOBAL.SAMPLING_MODE',
  INFORMATIVE_VARIABLES = 'GLOBAL.INFORMATIVE_VARIABLES',
  DISCRETIZATION = 'GLOBAL.DISCRETIZATION',
  VALUE_GROUPING = 'GLOBAL.VALUE_GROUPING',
  SELECTED_VARIABLES_PAIRS = 'GLOBAL.SELECTED_VARIABLES_PAIRS',
  SELECTED_VARIABLES = 'GLOBAL.SELECTED_VARIABLES',
  CONSTRUCTED_VARIABLES = 'GLOBAL.CONSTRUCTED_VARIABLES',
  EVALUATED_VARIABLES_PAIRS = 'GLOBAL.EVALUATED_VARIABLES_PAIRS',
  INFORMATIVE_VARIABLES_PAIRS = 'GLOBAL.INFORMATIVE_VARIABLES_PAIRS',
}

/**
 * Enumeration for display types in information blocks
 */
export enum DISPLAY_TYPE {
  GAUGE = 'gauge',
  METRIC = 'metric',
  TABLE = 'table',
}
