/*
 * Copyright (c) 2023-2025 Orange. All rights reserved.
 * This software is distributed under the BSD 3-Clause-clear License, the text of which is available
 * at https://spdx.org/licenses/BSD-3-Clause-Clear.html or see the "LICENSE" file for more details.
 */

export enum LS {
  SHOW_DIMNSION_STATS = 'SHOW_DIMNSION_STATS',
  SETTING_MATRIX_CONTRAST = 'SETTING_MATRIX_CONTRAST',
  COOKIE_CONSENT = 'COOKIE_CONSENT',
  OPEN_FILE = 'OPEN_FILE',
  CHANNEL = 'CHANNEL',
  SPLIT_SIZES = 'SPLIT_SIZES',
  VIEWS_LAYOUT = 'VIEWS_LAYOUT',
  AG_GRID_GRAPH_OPTION = 'AG_GRID_GRAPH_OPTION',
  CELL_AG_GRID = 'CELL_AG_GRID',
  COLUMNS_AG_GRID = 'COLUMNS_AG_GRID',
  OPTIONS_AG_GRID_SEARCH = 'OPTIONS_AG_GRID_SEARCH',
  MODES_AG_GRID = 'MODES_AG_GRID',
  OPTIONS_AG_GRID = 'OPTIONS_AG_GRID',
  MATRIX_TYPE_OPTION = 'MATRIX_TYPE_OPTION',
  UUID = 'UUID',
  MATRIX_TARGET_OPTION = 'MATRIX_TARGET_OPTION',
  MATRIX_MODE_OPTION_INDEX = 'MATRIX_MODE_OPTION_INDEX',
  TARGET_LIFT = 'TARGET_LIFT',
  SETTING_NUMBER_PRECISION = 'SETTING_NUMBER_PRECISION',
  TARGET_DISTRIBUTION_GRAPH_OPTION = 'TARGET_DISTRIBUTION_GRAPH_OPTION',
  MATRIX_MODE_OPTION = 'MATRIX_MODE_OPTION',
  SELECTED_TRAIN_PREDICTOR = 'SELECTED_TRAIN_PREDICTOR',
  DISTRIBUTION_GRAPH_OPTION_X = 'DISTRIBUTION_GRAPH_OPTION_X',
  DISTRIBUTION_GRAPH_OPTION_Y = 'DISTRIBUTION_GRAPH_OPTION_Y',
  SETTING_HYPERTREE_VISU_PURITY = 'SETTING_HYPERTREE_VISU_PURITY',
  SETTING_HYPERTREE_VISU_POPULATION = 'SETTING_HYPERTREE_VISU_POPULATION',
  SETTING_PERSIST_SCALE_OPTIONS = 'SETTING_PERSIST_SCALE_OPTIONS',
}
