export enum TYPES {
	FREQUENCY = "GLOBAL.FREQUENCY",
	COVERAGE = "GLOBAL.COVERAGE",
	LOGARITHMIC = "logarithmic",
	LINEAR = "linear",
	STANDARD = "GLOBAL.STANDARD",
	NUMERICAL = 'Numerical',
	CATEGORICAL = 'Categorical'
}
